# Generated by Django 4.2.7 on 2023-12-20 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='site_pictures/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=400)),
                ('amount', models.IntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material_type', models.CharField(max_length=20)),
                ('supplier_name', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('vehicle_no', models.CharField(max_length=20)),
                ('challan_no', models.CharField(max_length=20)),
                ('remark', models.TextField(max_length=500)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='MachineryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('machine_type', models.CharField(max_length=50)),
                ('supplier_name', models.CharField(max_length=50)),
                ('registration_no', models.CharField(max_length=20)),
                ('hours_worked', models.DurationField()),
                ('challan_no', models.CharField(max_length=20)),
                ('remark', models.TextField(max_length=500)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_sites.site')),
            ],
        ),
    ]
