# Generated by Django 4.2.7 on 2023-12-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_sites', '0002_machineryreport_image_materialreport_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialreport',
            old_name='image',
            new_name='material_image',
        ),
        migrations.RemoveField(
            model_name='machineryreport',
            name='image',
        ),
        migrations.RemoveField(
            model_name='siteexpensereport',
            name='image',
        ),
        migrations.AddField(
            model_name='machineryreport',
            name='machinary_image',
            field=models.ImageField(blank=True, null=True, upload_to='machinary_reports/'),
        ),
        migrations.AddField(
            model_name='siteexpensereport',
            name='expense_image',
            field=models.ImageField(blank=True, null=True, upload_to='expense_reports/'),
        ),
    ]
