# Generated by Django 5.0.6 on 2024-07-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
